
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team02-s23-5pm-3
owner: ucsb-cs156-s23
repo_name: team02-s23-5pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjU2MDQ5Njk1","is_bot":false,"login":"Anthonypella","name":""},"headRefName":"anthony_fixed_park_name","number":56,"title":"fixed name","url":"https://github.com/ucsb-cs156-s23/team02-s23-5pm-3/pull/56"},{"author":{"id":"U_kgDOB74XIA","is_bot":false,"login":"brOlivares","name":"Bryan Olivares"},"headRefName":"Bryan-Music","number":53,"title":"Bryan-Music Finished Entity, Repo and Controller","url":"https://github.com/ucsb-cs156-s23/team02-s23-5pm-3/pull/53"}]
